from fastapi import APIRouter

from schemas.ocorrencias_schemas import (
    AlineaCreateIn,
    AlineaOut,
    AlineaUpdateIn,
    ArtigoCreateIn,
    ArtigoOut,
    ArtigoUpdateIn,
    EstudanteCreateIn,
    EstudanteOut,
    EstudanteStatusIn,
    EstudanteUpdateIn,
    ImportacaoCsvOut,
    IncisoCreateIn,
    IncisoOut,
    IncisoUpdateIn,
    LeiCreateIn,
    LeiOut,
    LeiUpdateIn,
    OcorrenciaCreateIn,
    OcorrenciaEstudanteVinculadoIn,
    OcorrenciaOut,
    OcorrenciaProfessorVinculadoIn,
    OcorrenciaUpdateIn,
    RegimentoItemCreateIn,
    RegimentoItemOut,
    RegimentoItemStatusIn,
    RegimentoItemUpdateIn,
)
from routers.ocorrencias_base_legal_router import (
    buscar_alinea_api,
    buscar_artigo_api,
    buscar_inciso_api,
    buscar_lei_api,
    criar_alinea_api,
    criar_artigo_api,
    criar_inciso_api,
    criar_lei_api,
    listar_alineas_api,
    listar_artigos_api,
    listar_incisos_api,
    listar_leis_api,
    remover_alinea_api,
    remover_alinea_fallback_api,
    remover_artigo_api,
    remover_artigo_fallback_api,
    remover_inciso_api,
    remover_inciso_fallback_api,
    remover_lei_api,
    remover_lei_fallback_api,
    router as base_legal_router,
    atualizar_alinea_api,
    atualizar_artigo_api,
    atualizar_inciso_api,
    atualizar_lei_api,
)
from routers.ocorrencias_estudantes_router import (
    atualizar_estudante_api,
    atualizar_status_estudante_api,
    buscar_estudante_api,
    criar_estudante_api,
    importar_estudantes_arquivo_api,
    listar_estudantes_api,
    remover_estudante_api,
    remover_estudante_fallback_api,
    router as estudantes_router,
)
from routers.ocorrencias_regimento_router import (
    atualizar_regimento_item_api,
    atualizar_status_regimento_item_api,
    buscar_regimento_item_api,
    criar_regimento_item_api,
    importar_regimento_itens_arquivo_api,
    listar_regimento_itens_api,
    remover_regimento_item_api,
    remover_regimento_item_fallback_api,
    router as regimento_router,
)
from routers.ocorrencias_registros_router import (
    atualizar_ocorrencia_api,
    atualizar_ocorrencia_parcial_api,
    buscar_estudantes_ocorrencia_api,
    buscar_ocorrencia_api,
    buscar_professores_ocorrencia_api,
    criar_ocorrencia_api,
    gerar_pdf_ocorrencia_api,
    listar_ocorrencias_api,
    listar_opcoes_ocorrencias,
    remover_ocorrencia_api,
    remover_ocorrencia_fallback_api,
    router as registros_router,
)

router = APIRouter()
router.include_router(registros_router)
router.include_router(estudantes_router)
router.include_router(base_legal_router)
router.include_router(regimento_router)
